#
# do not commit, commit encrypted secret
#
# Here it is committed only for learning purposes.
#
apiVersion: v1
kind: Secret
metadata:
    namespace: devops
    name: todo-postgres
    labels:
        app: todo
stringData:
    db: todo
    url: jdbc:postgresql://postgres-svc:5432/todo
    username: ENC[AES256_GCM,data:wxeq5PRBFUQ=,iv:1LbK3QLfR1Yz5APzcXkClq4L++/8BEaka6tmSqyVwtc=,tag:OQeyuzc3WFB/NoXj61h15g==,type:str]
    password: ENC[AES256_GCM,data:agVQ94wNfJX/9E6e,iv:F6KzZCOAWMd8qnuqZFGuV/dKyRAB+KcMTSzPk7b3O3s=,tag:HLsY5+Os4Tw20Sak+Y6ntw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ssqylrszr8sj6ys8glqhrr7w0zkdve80kyndcsuhu3qsx3zywaxsxph2z0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Rklpb0pxNkxCWk9tSE5B
            WFNSZzlTUlk3QVVPczZ5eXZVam9SZ3RhZkNVCmpzOWxxVWJvQXBpRlJGd2pLaFph
            SHVqeWRyc1lUbEVESjZCTDJzOXZtSE0KLS0tIGYzMXFBMkVSMVFyRGlFQUF3QjZ5
            UW5DbzIwWFhRaUV3WjlqYzFkcDIvNGsKqbcbblv/XrSgyWISMvq719EIo7Yx7Aay
            618VO6JQHDhNfKihuKshuhneINKtVJyh3PAmdkL9182sEPwH79S+wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-14T15:04:25Z"
    mac: ENC[AES256_GCM,data:ShndagBkIPzvmngfLaCZYxhPEwYlsCAOvwXSydxV/2ZeilPX613YljilEKYPZaSmCQM4sWRaT1TV1oigJxXgGhTX1agmBmI8DO70ogWtWlBX94HSNi2hdwEeCDNWnIiO1y2va3d7tT1nh/hmkiPN3mYG+/WOWKgsCbeC/JpxFgI=,iv:9QoAndaFuhzqoA4nvn3AsvITNm49DnDnPnv8/Ar15rw=,tag:DavM/Y/eSTyR3DNlzLTu+w==,type:str]
    pgp: []
    encrypted_regex: ^(username|password)$
    version: 3.7.3
