apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: persistent-volume-claim
      containers:
        - name: todo-app
          image: mikhailzvagelsky/devopswithkubernetes_todo:1.13
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          volumeMounts:
            - name: shared-volume
              mountPath: /home
