apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops
  name: persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
