apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: todo-back-service
spec:
  type: ClusterIP
  selector:
    app: todo-app-back
  ports:
    - name: back-svc-port
      port: 8091          # The service is listening on this port.
      protocol: TCP
      targetPort: app-port
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: devops
  name: todo-storage-class
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops
  name: todo-image-storage-clm
spec:
  storageClassName: todo-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: todo-app-back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-back
  template:
    metadata:
      labels:
        app: todo-app-back
    spec:
      containers:
        - name: todo-app-back
          image: mikhailzvagelsky/devopswithkubernetes_todo:2.10
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
              name: app-port
          readinessProbe:
            httpGet:
              port: 8091
              path: /todos
          livenessProbe:
            httpGet:
              port: 8091
              path: /todos
          startupProbe:
            httpGet:
              port: 8091
              path: /todos
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: POSTGRES_CREDENTIALS_FOLDER
              value: "/secrets"
          volumeMounts:
            - name: shared-volume  # used to store daily image in it
              mountPath: /home
            - name: secret
              mountPath: "/secrets"
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: todo-image-storage-clm
        - name: secret
          secret:
            secretName: todo-postgres
            defaultMode: 0400

