#
# do not commit, commit encrypted secret
#
# Here it is committed only for learning purposes.
#
apiVersion: v1
kind: Secret
metadata:
  namespace: devops
  name: todo-postgres
  labels:
    app: todo
stringData:
  db: todo
  url: jdbc:postgresql://postgres-svc:5432/todo
  username: todouser
  password: todoPassword
