apiVersion: batch/v1
kind: Job
metadata:
  name: todo-job
spec:
  template:
    spec:
      containers:
        - name: todo-job
          image: mikhailzvagelsky/todo_script:v1
          env:
            - name: BACKEND_URL
              value: "http://todo-back-service:8091/todos"
      restartPolicy: Never