apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cronjob
              image: mikhailzvagelsky/todo_script:v1
              imagePullPolicy: IfNotPresent
              env:
                - name: BACKEND_URL
                  value: "http://todo-back-service:8091/todos"
          #          restartPolicy: OnFailure
          restartPolicy: Never